name: Fetch files from service repositories
on:
  push:
    branches:
      - main

env:
  MAIN_BRANCH: "main"

concurrency:
  group: "fetch-files"
  cancel-in-progress: true

jobs:
  fetch-service-1:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global credential.helper store
      - name: Install python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install git-filter-repo==2.38.0
      - name: Checkout docs repository
        uses: actions/checkout@v2
      - name: Fetch files from Service 1 Repository
        uses: ./.github/actions/fetch-files
        with:
          fetch-depth: 0
          repository: ali-ozturk/docs-prot-service-1
          ref: main
          path: service