name: Fetch files from service repositories
on:
  push:
    branches:
      - main
jobs:
  fetch-files:
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: "docs"
    steps:
      - name: Configure Git as Github Actions
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global credential.helper store
      - name: Checkout docs repository
        uses: actions/checkout@v2
      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install git-filter-repo
      - name: Checkout service repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ali-ozturk/docs-prot-service-1
          ref: main
          path: service
      - name: Merge specific files from service repository into docs repository
        run: |
          cd service
          git checkout -b merge-branch
          git filter-repo --paths-from-file ./files-to-docs.txt --to-subdirectory-filter $FOLDER_NAME --path-rename ""=$FOLDER_NAME/ --force
          cd $GITHUB_WORKSPACE
          git remote add service $GITHUB_WORKSPACE/service
          git fetch service
          git merge --allow-unrelated-histories service/merge-branch
          git push origin main
      - uses: actions/checkout@v3
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3