on:
  push:
    branches:
      - main

jobs:
  push_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "test@test.com"
          git config --global user.name "Github Workflows"
          git config --global credential.helper store

      - name: Copy Files to Another Repository
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/Ali-Ozturk/docs-prot-shared-cos.git
          target_dir=docs-prot-shared-cos/docs
          cp ./docs/. $target_dir/
          cd docs-prot-shared-cos
          git add .
          git commit -m "Update files"
          git remote set-url origin "https://github.com/Ali-Ozturk/docs-prot-shared-cos.git"
          git push origin HEAD:main